modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="remnant_bosses"
version="2.0.1"
displayName="Remnant Bosses"
displayURL="https://www.nightbeam.cloud"
logoFile="logo.png"
credits="no credits"
authors="NAIZO"
description="Face the deadliest bosses ever forged combat, fights, and chaos await!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.remnant_bosses]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="AFTER"
side="BOTH"

[[dependencies.remnant_bosses]]
modId="jauml"
mandatory=true
versionRange="[1.2.0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.memory_of_the_past]]
modId="jauml"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
# End of user code block dependencies configuration
